# Generated by Django 5.1.3 on 2025-12-11 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default='Untitled Session', help_text='Name of the simulation session', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the simulation session')),
                ('automata_type', models.CharField(choices=[('DFA', 'Deterministic Finite Automaton'), ('NFA', 'Nondeterministic Finite Automaton'), ('TM', 'Turing Machine'), ('REGEX', 'Regular Expression')], db_index=True, default='DFA', max_length=10)),
                ('automata_data', models.JSONField(help_text='JSON representation of the automata configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier for sharing sessions', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulation Session',
                'verbose_name_plural': 'Simulation Sessions',
                'db_table': 'simulation_sessions',
                'ordering': ['-last_accessed_at'],
                'permissions': [('can_share_session', 'Can share sesstion with others'), ('can_view_others_sessions', 'Can view sessions shared by others')],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.CharField(help_text='The input string tested', max_length=1000)),
                ('is_accepted', models.BooleanField(help_text='Whether the automaton accepted this input')),
                ('execution_time', models.FloatField(help_text='Execution time in milliseconds')),
                ('result_steps', models.JSONField(help_text='Step-by-step simulation trace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='simulations.simulationsessions')),
            ],
            options={
                'verbose_name': 'Simulation Run',
                'verbose_name_plural': 'Simulation Runs',
                'db_table': 'simulation_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='simulationsessions',
            index=models.Index(fields=['user', '-created_at'], name='simulation__user_id_c2dac8_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsessions',
            index=models.Index(fields=['is_favorite'], name='simulation__is_favo_296cb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='simulationsessions',
            constraint=models.UniqueConstraint(fields=('user', 'session_name'), name='unique_session_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['session', '-created_at'], name='simulation__session_8c8f2c_idx'),
        ),
    ]
