name: Check Secrets Configuration

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths: [ '.github/workflows/**' ]

jobs:
  check-secrets:
    name: Verify Secrets Setup
    runs-on: ubuntu-latest
    steps:
      - name: Check Vercel Secrets
        run: |
          echo "## Secrets Configuration Check" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Check Vercel secrets
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "✅ VERCEL_TOKEN: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ VERCEL_TOKEN: Missing" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "✅ VERCEL_ORG_ID: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ VERCEL_ORG_ID: Missing" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "✅ VERCEL_PROJECT_ID: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ VERCEL_PROJECT_ID: Missing" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Check Firebase Secrets
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Firebase Configuration" >> $GITHUB_STEP_SUMMARY
          
          # Check Firebase secrets
          if [ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" ]; then
            echo "✅ NEXT_PUBLIC_FIREBASE_API_KEY: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ NEXT_PUBLIC_FIREBASE_API_KEY: Missing" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" ]; then
            echo "✅ NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: Missing" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" ]; then
            echo "✅ NEXT_PUBLIC_FIREBASE_PROJECT_ID: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ NEXT_PUBLIC_FIREBASE_PROJECT_ID: Missing" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" ]; then
            echo "✅ NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: Missing" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" ]; then
            echo "✅ NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: Missing" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" ]; then
            echo "✅ NEXT_PUBLIC_FIREBASE_APP_ID: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ NEXT_PUBLIC_FIREBASE_APP_ID: Missing" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -n "${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" ]; then
            echo "✅ NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: Configured" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: Missing" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "If any secrets are missing:" >> $GITHUB_STEP_SUMMARY
          echo "1. Go to: https://github.com/SifatAli008/TOC-Simulator/settings/secrets/actions" >> $GITHUB_STEP_SUMMARY
          echo "2. Add the missing secrets as shown in SETUP_SECRETS.md" >> $GITHUB_STEP_SUMMARY
          echo "3. Run this workflow again to verify" >> $GITHUB_STEP_SUMMARY
