name: Dependency Updates

on:
  schedule:
    - cron: '0 9 * * 1'  # Run every Monday at 9 AM UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update npm dependencies
        run: |
          npx npm-check-updates -u
          npm install

      - name: Run tests
        run: |
          npm run test:ci
          npm run build
        env:
          CI: true
          SKIP_ENV_VALIDATION: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: '🔄 Automated Dependency Updates'
          body: |
            ## 🔄 Automated Dependency Updates
            
            This PR contains automated dependency updates generated by the dependency update workflow.
            
            ### Changes
            - Updated npm dependencies to latest compatible versions
            - All tests pass with updated dependencies
            - Build succeeds with new dependency versions
            
            ### Verification
            - ✅ Tests passing
            - ✅ Build successful
            - ✅ No breaking changes detected
            
            Please review the changes and merge if everything looks good.
          branch: automated/dependency-updates
          delete-branch: true

  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Audit dependencies
        run: npm audit --audit-level=high

      - name: Fix security vulnerabilities
        run: npm audit fix

      - name: Create security update PR
        uses: peter-evans/create-pull-request@v5
        if: success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'security: fix dependency vulnerabilities'
          title: '🔒 Security: Fix Dependency Vulnerabilities'
          body: |
            ## 🔒 Security Updates
            
            This PR contains automated security fixes for dependency vulnerabilities.
            
            ### Security Fixes
            - Applied `npm audit fix` to resolve security vulnerabilities
            - Updated vulnerable dependencies to secure versions
            
            ### Verification
            Please review the security updates and test thoroughly before merging.
          branch: automated/security-updates
          delete-branch: true
